Docker:
	docker build --no-cache -t potatofields/livecursors:frontendv1 --push .

Push:
	docker push potatofields/livecursors:frontendv1

Run:
	docker run -p 3000:80 potatofields/livecursors:frontendv1
